description: IOs - 'The input required for the workflow is a ProductNameModel, which
  is a subclass of pydantic.BaseModel and contains a single ''product_name'' field
  (str). The output of this workflow will be a FileModel (subclassed from pydantic.BaseModel
  as well), which contains a ''file_path'' field (str) for the path of the created
  spreadsheet.
input-class: ProductNameModel
name: AmazonTop50ProductsReviews
output-class: FileModel
parameters: {}
